project:
  type: website

website:
  title: "STA4173 - Biostatistics - Summer 2025"
  navbar:
    left:
      - href: files/schedule.qmd
        text: Schedule
      - href: files/syllabus.qmd
        text: Syllabus
      - href: files/get_help.qmd
        text: Need Help?

format:
  html:
    theme: minty
    css: styles.css
    toc: false
